services:
  db:
    image: mariadb:11.3.2-jammy
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: root_db
      MARIADB_USER: user
      MARIADB_PASSWORD: user
      TZ: Europe/Berlin
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - "./mariadb_data:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

  php-app:
    build:
      context: ../src/api/php
      dockerfile: ../../../config/Dockerfile
    volumes:
      - ../src/api/php:/var/www/html
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:80"

  frontend:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ../src/public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4000:80"
    depends_on:
      - php-app
